FROM node:18-alpine

ARG NODE_ENV
ARG PORT
ARG DB_NAME
ARG DB_USER
ARG DB_HOST
ARG DB_PASSWORD
ARG DB_PORT
ARG GOOGLE_CLOUD_API_KEY
ARG JWT_SECRET
ARG SESSION_SECRET
ARG GOOGLE_CLOUD_ID
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG OPENAI_API_KEY
ARG REDIS_SECRET
ARG REDIS_HOST
ARG REDIS_PORT
ARG PAT
ARG USER_ID
ARG APP_ID
ARG MODEL_ID
ARG TEXT_MODEL_USER_ID
ARG TEXT_MODEL_APP_ID
ARG TEXT_MODEL_VERSION_ID
ARG TEXT_MODEL_ID
ARG MODEL_VERSION_ID
ARG CLOUDINARY_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG DATABASE_URL
ARG AZURE_ACCOUNT_NAME
ARG AZURE_ACCOUNT_KEY
ARG AZURE_CONTAINER_NAME
ARG SPEECH_KEY
ARG SPEECH_REGION
ARG HOST_EMAIL_ADDRESS
ARG HOST_EMAIL_PASSWORD

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_HOST=${DB_HOST}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
ENV JWT_SECRET=${JWT_SECRET}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV GOOGLE_CLOUD_ID=${GOOGLE_CLOUD_ID}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV REDIS_SECRET=${REDIS_SECRET}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV PAT=${PAT}
ENV USER_ID=${USER_ID}
ENV APP_ID=${APP_ID}
ENV MODEL_ID=${MODEL_ID}
ENV TEXT_MODEL_USER_ID=${TEXT_MODEL_USER_ID}
ENV TEXT_MODEL_APP_ID=${TEXT_MODEL_APP_ID}
ENV TEXT_MODEL_VERSION_ID=${TEXT_MODEL_VERSION_ID}
ENV TEXT_MODEL_ID=${TEXT_MODEL_ID}
ENV MODEL_VERSION_ID=${MODEL_VERSION_ID}
ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
ENV AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
ENV AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
ENV SPEECH_KEY=${SPEECH_KEY}
ENV SPEECH_REGION=${SPEECH_REGION}
ENV HOST_EMAIL_ADDRESS=${HOST_EMAIL_ADDRESS}
ENV HOST_EMAIL_PASSWORD=${HOST_EMAIL_PASSWORD}

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

# Generate Prisma client
RUN npx prisma generate

# Build the backend
RUN npm run build

CMD ["npm", "run", "start"]
